name: test-design
description: Partager des recherches, des tutoriaux pour peut-etre un meilleur developpement web…
baseurl: /tips 

twitter_username: lvdesign
github_username:  lvdesign
instagram_username: lvdesignfr


# Build settings
markdown: kramdown
highlighter: rouge

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    
    
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  svg-icons,
  svg-decorations,
  scss,
  .sass-cache,
  readme.md
]